name: scitt
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cryptography=39.0.0
  - exceptiongroup=1.1.0
  - flask=2.2.2
  - httpcore=0.16.3
  - httpx=0.23.3
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - markupsafe=2.1.2
  - ncurses=6.3
  - openssl=1.1.1s
  - pytest=7.2.1
  - python=3.8.16
  - rfc3986=1.5.0
  - setuptools=66.1.1
  - wheel=0.38.4
  - pip=22.3.1
  - pip:
    - asn1crypto==1.5.1
    - cbor2==5.4.6
    - certvalidator==0.11.1
    - pycose==1.0.1
    - ecdsa==0.18.0
    - oscrypto==1.3.0
    - rkvst-archivist=0.20.0
    - six==1.16.0
